#!/bin/bash
# gaming-500 → 720p/15Hz HDF5 编码上传(unjustify/gaming500-720p-hdf5,公开)。
# 断点续跑:先把 manifest 放回 runs/data/g500_h5/manifest.json(HF 仓库根目录
# 或 tests/manifest_gaming500_720p.json 均有存档),再直接重跑本脚本即可——
# 已封片会话自动跳过,未封片(shard_0001 起)的段重做。GPU 实例上自动走 NVDEC。
set -e
cd "$(dirname "$0")/.."
mkdir -p runs/data/g500_h5 runs/logs
[ -f runs/data/g500_h5/manifest.json ] || cp tests/manifest_gaming500_720p.json runs/data/g500_h5/manifest.json
HF_XET_HIGH_PERFORMANCE=1 PYTHONPATH=. python3 tests/encode_gaming500_hdf5.py \
  --games "007,007-first-light,2xko,ac4,age-of-empires,aim-lab,aimlabs,alan-wake,angry-birds,angry-birds-2,arc-raiders,asphalt-9,asphalt8,assassin-s-creed,assassins-creed,assassins-creed-odyssey,assassins-creed-rogue,assassins-creed-syndicate,avatar-frontiers-of-pandora,balatro,batman,batman-arkham-asylum,beach-buggy-racing,bermuda-adventures,bgmi,bioshock,black-myth-wukong,blackjacket,blackshard,bombsquad,bounty-rush,brawlhalla,buckshot-roulette,bus-simulator,call-of-duty,candy-crush,car-dealer-simulator,chained-together,chess,clash-of-clans,clone-drone,cod-mw2,counter-strike-2,cricket07,crimson-desert,cuphead,cyberpunk-2077,dead-as-disco,death-stranding,divinity-original-sin-2,dota-2,ea-fc-26,ea-sports-fc-25,ea-sports-fc-26,ea-sports-fc26,elden-ring,epsxe,euro-truck-simulator,euro-truck-simulator-2,fall-guys,far-cry-4,far-cry-5,farming-simulator,fears-to-fathom,fifa-16,firework,fivem,flight-simulator,fortnite,forza-horizon,forza-horizon-3,forza-horizon-5,free-fire,free-fire-max,gear-club,gear-club-unlimited-2,genshin-impact,geometry-dash,ghost-of-tsushima,god-of-war,got-kingsroad,grand-theft-auto-san-andreas,grand-theft-auto-v,grand-theft-auto-vice-city,gta-other,gta-samp,gta-san-andreas,hill-climb-racing,hitman-3,hogwarts-legacy,honkai-star-rail,horizon-zero-dawn,just-cause-2,kingsroad,last-of-us,mafia-the-old-country,marathon,max-payne-3,minecraft,mini-metro,nathan-morgan-dilemma,need-for-speed,nfs-payback,nfs-underground-2,no-mans-sky,nte,one-piece,one-piece-bounty-rush,ori,ori-and-the-blind-forest,ori-and-the-will-of-the-wisps,pacify,painted-in-blood,palworld,pcsx2,phasmophobia,pokemon,ppsspp,pragmata,prince-of-persia,pubg-bgmi,reanimal,resident-evil,resident-evil-2,resident-evil-4,resident-evil-7,restaurats,riders-republic,rise-of-the-tomb-raider,road-96,rocket-league,rpcs3,schedule-i,sekiro,skyrim,sleeping-dogs,solitaire,solo-leveling,solo-leveling-arise,south-of-midnight,spider-man,spider-man-2,split-fiction,stronghold-crusader,stumble-guys,swat-commander,tekken,tekken-3,tekken-4,tekken-6,tekken-7,tekken-tag-tournament,terraria,the-crew-2,the-division,the-finals,the-last-of-us,the-last-of-us-2,this-bed-we-made,township,ultrakill,uncharted,valorant,watch-dogs,wolfenstein,wuthering-waves,wwe2k25" \
  --n 999 --parallel 8 --buffer-gb 16 > runs/logs/encode.log 2>&1
