"""Godot 强化学习环境、通信与训练入口。

显式 re-export，禁止桶式 `import *`（命名空间透明，承 code_conventions §2.5）。
"""

from .godot_process import launch_godot, terminate_godot_process
from .shared_memory_environment import (
    ACT_SEQ_OFFSET,
    CHANNELS,
    CONT_DIM,
    CONT_OFFSET,
    DISC_DIM,
    DISC_OFFSET,
    GODOT_EXE,
    IMAGE_HEIGHT,
    IMAGE_WIDTH,
    IS_WINDOWS,
    M_DONE,
    M_FRAME,
    M_REWARD,
    M_SIM_DT,
    M_STEPS,
    META_OFFSET,
    META_PER_ENV,
    NUM_ENVS,
    OBS_SEQ_OFFSET,
    PROJECT_DIR,
    SEQ_OFFSET,
    TOTAL_SHM_SIZE,
    TRAIN_SCENE,
    GodotTrainingEnvironment,
    reset_timer_resolution,
    set_timer_resolution,
    shared_memory_path,
)

__all__ = [
    "ACT_SEQ_OFFSET",
    "CHANNELS",
    "CONT_DIM",
    "CONT_OFFSET",
    "DISC_DIM",
    "DISC_OFFSET",
    "GODOT_EXE",
    "IMAGE_HEIGHT",
    "IMAGE_WIDTH",
    "IS_WINDOWS",
    "META_OFFSET",
    "META_PER_ENV",
    "M_DONE",
    "M_FRAME",
    "M_REWARD",
    "M_SIM_DT",
    "M_STEPS",
    "NUM_ENVS",
    "OBS_SEQ_OFFSET",
    "PROJECT_DIR",
    "SEQ_OFFSET",
    "TOTAL_SHM_SIZE",
    "TRAIN_SCENE",
    "GodotTrainingEnvironment",
    "launch_godot",
    "reset_timer_resolution",
    "set_timer_resolution",
    "shared_memory_path",
    "terminate_godot_process",
]
